/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
 /* tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  VueJsSidebar: [{type: 'autogenerated', dirName: '.'}],
  LaravelSidebar: [{type: 'autogenerated', dirName: '.'}],*/

  // But you can create a sidebar manually
  
  VueJsSidebar: [
    {
      type: 'category',
      label: 'Tutorials',
      items: ['VueJs/tutorials/intro',
      'VueJs/tutorials/editingconnection',
      'VueJs/tutorials/migrations',
      'VueJs/tutorials/frontquasar'],
    },
    {
      type: 'category',
      label: 'Installation',
      items: ['VueJs/installation/prerequisites',
      'VueJs/installation/installinginaproject',],
    },
    {
      type: 'category',
      label: 'Guides',
      items: ['VueJs/guides/crud'],
    },
    {
      type: 'category',
      label: 'Diagrams',
      items: ['VueJs/diagrams/entity-relation'],
    },
    {
      type: 'category',
      label: 'Modules',
      items: [{type: 'autogenerated', dirName: 'VueJs/modules'}],
    },
    {
      type: 'category',
      label: 'Testing',
      items: [{type: 'autogenerated', dirName: 'VueJs/testing'}],
    },    
    {
      type: 'category',
      label: 'Wiki',
      items: ['VueJs/wiki/glossary',
      'VueJs/wiki/goodpractices'],
    },
  ],
};

module.exports = sidebars;
