/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // But you can create a sidebar manually
  
  VueJsSidebar: [
    {type: 'autogenerated', dirName: 'VueJs'}
  ],
  LaravelSidebar: [
    {
      type: "category",
      label: "Tutorials",
      items: [{type: "autogenerated", dirName: "Laravel/tutorial"}]
    },
    {
      type: 'category',
      label: 'Modules',
      items: [{type: 'autogenerated', dirName: 'Laravel/modules'}],
    },
    {
      type: 'category',
      label: 'i18n',
      items: [{type: 'autogenerated', dirName: 'Laravel/locale'}],
    },
    {
      type: 'category',
      label: 'API',
      items: [{type: 'autogenerated', dirName: 'Laravel/API'}],
    }
  ],
  N8NSidebar: [],
  BlockSidebar: [
    {type: 'autogenerated', dirName: 'blocks'}
  ],
};

module.exports = sidebars;
